spring:
  application:
    name: harullala

  # H2 인메모리 데이터베이스 설정 (개발용)
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

# OpenAI API 설정
openai:
  api:
    key: ${OPENAI_API_KEY:}
    url: https://api.openai.com/v1/chat/completions
    model: gpt-3.5-turbo # Default model, can be overridden by user